apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Or0I0FutVeA0blUgt9oSJmo8Do8r1O4Y+HLi9pc6gZK5SnN/4l6GKg==,iv:kefbMvnmzvkC2DcweL/WiDi6XsTy06B8UQYMY6TOyNM=,tag:MBTOsCeBPFxZVB0rmuib0A==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVUY0V2M5SldZWU1PWEhj
        QUNQakZOM0VjWlM5R0R5d2dEWCtuSG1TYUIwCmxSdmdDZEdEL3dyVzlZUnBtdGQ1
        UW4vMmkrT2ZiN05oaWErdGxzQ0NidGMKLS0tIDhVOENseTg3bDlad2ExUGJUOC9Z
        VTV1Rjl6UTBncHpTVHVHc1NYMlhkSlEKdnhbY/+UqJws7Tb6llHg0FnZATWk08ou
        V6horpNYCiQRINw2GwE854zUtg9dDhJGWqgTUfB+ff+QqnDVgP7tww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T04:15:30Z"
  mac: ENC[AES256_GCM,data:GoWW40D8q40kL2vaP+kuL8rcDMAEHSE8IKH7zh6ghpRIhnusXWo5JBZrXETNr81Q2/r0FhS4x1Nc0ORLmKBqzookfYNnBv2XJisOI+0FeAG9Cvu2aa3hvj2YfkAe6j1/8+hLzvH1xg9PZPMGZ3lluAsWyZl7PtU9eErsTFQRxJg=,iv:DkxrwXo3ZEauMXLuH0dHCtgTS1QOHXPCk4jijX3OgFI=,tag:516WaSnisXb8GBSyTWkDSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
