apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eysKXKfkp68EYUFawX0YG6LpVEPUxE2pSm/1owpbqlnZphalJoZURQ==,iv:6BRJWEU/AGEvyrPUSyX+dCYJl3M8/a5nymq2/e/6DGE=,tag:RQKRq9d7FP7opumAd79FIA==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dWgxSGlpMkFmODQ0Uitj
        QnVZbnJtb0czYlpQVno4UlFHRVV5WS9QcjFnClN1cEtYM1BaZ2NqVGxqR1V4S2M4
        R1I0N0tYeUJ0Sk5ocEMxVm5iYlRFS1kKLS0tIDFwb1A0UkJhLzZIaTJoN3hVOTBz
        aTlqTUdZNys1cDVxVG80ZFJiYjE4RWsK3GHwouQ9tc/OveKWfWM021AD1HHlNdyS
        hDNLqQuImqBeu8tLQltXs/qL/gY1kYF8NkaRZ647ughIa7vT2jNOvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T05:31:52Z"
  mac: ENC[AES256_GCM,data:x5h6G9qAZ1/chlK7SahqcjgYaLpjdjBOcBlvvOoJtfgmVk2jBsoM3NXTK4qqoWEJkWqsGsKIue2QXHPGCCHVoCUKw5TPy0RPJZM+nhvotyt00+iDRGgHJBhCQG6PklRanUU0Q5gef6vV2ZkEU9xpKcPkDgazSc92oWyogw6hOSg=,iv:0G3f0ZnvciTxLkfI48eyO23eMPfLfInjt4q1U1q8muA=,tag:gV4cOzeQGglcnYLKJtKtSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
