apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:onP/miGhb82/,iv:HBugvHD7a00dcBHvaEU14KcgmUff4Cmt6s24HUZItig=,tag:JpGlcjFCFD4GlulbLGvT2w==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK1ZDNzYwaSszV3Q4V0p6
        TlE1Y3hXMnIrK245QzZzSTJhUGdmeDQxSFE4CllDc1NpNjIxSC9ZcDNYbzI0ZHhy
        bzlsdnltcDNTdGx1NGFQRXdhcHBIZzAKLS0tIFF6TW9FNS9xcThMZE0yKzNPM1Vs
        ZHMyZlJTMlRmNGlVWndWclpUOFQwUUUK61sJPU3eDOGR/Ln/aytURGvQVRGEQ4x4
        b7nCerP3WPhGNayf8u/cIUOiv8bvfyH2bOOj5Bepyxjngojv9/2wyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T05:31:52Z"
  mac: ENC[AES256_GCM,data:ONgZzHYcAXOuD84/qkCclewRZN0/2idXMCbwCDdsibuuDCcRALAmu8kBaZ+LByBHxP+hBNA/XtHxrMA8CzOxSrNttKnJqGIzYXVAjJamQmClBEgMHMZt6nHoXxTlXk+Z6oiSwWMG4sTb29pKNwJTJxJp4QzUN+N3xyC3pAKy0wI=,iv:BtFBHiBLuex01RUs5E1B+mBg4hIlR66w7hXh4+1BDqA=,tag:KEdVYFMM3uogjZg9UPEfUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
