apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+KmecrpRL45p,iv:javvO3N7fNzSUAXgdpQ7ogHTCz1TPDC2U/R7gncykoo=,tag:77hBOoZyZt6uUIjAyrxdeQ==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN2IrS2VHcGlCYkE2ZzJY
        OGNRR2JRbU9QRUUyVXZ2djZMdFVkU3U1akRRCkpNcy9ybmozUlVXRnZwV25ONHBi
        SXpyNVpIWTJSYUZ3cjZvdU9hc253QVEKLS0tIFplVlJwNHk2MnRxTmpuYlh5TFYw
        NWZRN3AxZnBiZExUWFk4TVUxZTJrNVkKICK5jWEKGeYpyUBDNEG0fR57l+PNtuyR
        r93SaE1u+fxkF0j/BQ5yOJVRs6sPFCbH5owyGqlq+3ve0sbx+J7+nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T04:15:30Z"
  mac: ENC[AES256_GCM,data:VoImP6UW6BVsBTTUvCvCu7WKusZsr2r3GE/KBSsUMfU5aJw/n0FFqhGpFkyuSXtL+GwiWrK8by6sdIZ9gPBjOmzk7sz8uJ41vfRJXKYTRXAYLJVvbpwPZtkG3It4tcm8js8riDySYdPKWoJbZQJ4Bef/lXE2Vnmd1Gc/ZUk8kkE=,iv:c8IA/J25xktGB4jbV2W5+8TBzZ3dtBgMXv94xjwYD3c=,tag:yyWRnOl2qJNSJb8im9xBwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
