apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:xPQkMchb3QKxlnUjEmnj6GCatkqHB9CxmbU9vrP5dgs=,iv:655ls8wWV7Q39ZSueQInAoA85sJbsMUTWqo3FdfkD1U=,tag:Lf5G37ZxFHkkdfikw/bpyQ==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbWc2OWlXc3VVNU5xTHRU
        djc0cFFBbWlJU1JJZTFoaUIzaTdsVVM3dXk4CmF2RmEwcnEvcGdvdXBJWDhnZHFP
        WEZpR1lKVi94ZndjZ05pTTFiV0JwSVkKLS0tIDNoMjd5Y1BhZUtQNHBQTk1lZm9M
        cXNpRk5VRGRGY2hDb3Zndkc2cWsrazgKlsLsgJZ+mEa6sYdf++kmgy1tmtc2Q58d
        cCHk9suujzuhDNeSaptEm3t7fjZVc4aQfbgKIB+2sHAMrrnfqjoN5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T04:15:30Z"
  mac: ENC[AES256_GCM,data:oVr/h8D97mnWS/KUz+u9HGvzmhYsbSpArPpLGyvNvCBjpq0fFXV1X0omvUF9C8g67/X48I0IrvoXEs4ys1eISZhHt6MAMSfSzMrhSMggHlnE1/3jIh1zcPOFnEv5rCI3el/c/X8B6hHJl9lfflO6PwZXJ3zUJHXF1pt7GdNlIeQ=,iv:N4SSV8f1vSA0dMWgOFltBfm24XfxQVYcGtDQSd2c+W4=,tag:naSRKnRy0wW1PrpXDKvSqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
