apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:8hFQAS+KHXv0CWDa0PxTril5NtDofnJJfKPZQk4GWVA=,iv:fUb0mxKJw64ITgRRQihdWt1J5UZhGziw5t4EIVRgtwc=,tag:xCjTX1uZL9LN2PT9c6Cbug==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZUVBUDdpUUVYMmJqWXRV
        WUIwUXhvMmxsZG9uOE5JRVNJb0NIWHdzZGt3Cmg3TS9QQ0o5cHRBU2JUTkxtYVlB
        VzFpUjBXamJzdGs4ck9kT0N1ZmRyMTgKLS0tIDZoUDBxQkYvN20xWjFxYVZVclBG
        aFVGL211UTNZN2xkbU5tRWtpR2R3NU0K4uTC4vaZoOeDMOLjzk2am1c1lierjefV
        Ofs3uzDMYKIQg0xENX2s5iIER7Ha2fDs1hW2zlkWx1dZ7UX0Q4O+uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T05:31:52Z"
  mac: ENC[AES256_GCM,data:ngbjn0gccdDxj21LybCdQLDIxuneZdLaEWlJFu6KpgqrLhROaMZa2YyLftwquZuWvyg9IAYKMlS9wFYNI5MMQ+0Fk7RGjC/Gx0lf/vJ7CH4z3eBoUIz0WXACWStmIqBm0mT/NUG+2kncFcVq2jornmlRdI4ExbdquDSf6pdglKk=,iv:xKl0WlHfsRirFL0QStDGntax8S0NJgrA3aVEAglDlIw=,tag:Q4zSoQiWstU6XecMFySRwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
