apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Y9VEwXAGmOfN8rxXAghMDNq+9vDCHbXY5qlGM0P/K/fTUKL5KTY4U46Q1jFQgX3jGteuAxMrrYzHF5TWz1M8264fJ5HZH3H63tr0JN1JUtSM+b1cMIOpt05rawB4LdzRzaCQ/WfYDxqtk8Un/C48yzAxB27StzepzpeWBmpZnPsrZ5kzX7WGcqJhEwcGsU0XmoIVREvIkqkCvSq4L/+QpCbLsOfUhA2tPoii8Gy6bbO6c7FD,iv:GzZIRXs27TfHQTIgboC7AVDgS8GQmdLebnhS8+VAGSY=,tag:QBvv+cC30S2dyFcgWXagMQ==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TDN0bGdPU1hvekV6Tnpp
        OGtnWHFwZTNDTjRmYzJPbVRzcEEzWHNsYTFzCm9Zc0wvREpXVzhUTExJMmxBaFJ6
        MitQNHdqNlRBOWVPcUZ5QUhuMGdGMzgKLS0tIGtFUzdmU280eTF4YkRjZGV3TTNl
        eDFPWWEvVVRKcE51Nm55RW5jd3kxREkKwJeLLdBa01A8Ov29v/Y/2cpEIEM9FjG8
        Z9x5ZFuj9OS5SzM+jOPbbQgo42r/3emCOUUnEgJ6OIODW9uLYl5PHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T05:31:52Z"
  mac: ENC[AES256_GCM,data:37Gvll+qOANutPMQAgFCjg5yzivAIecXrEQBs0otOL9tuwyuJuSZj3p92MOcUvM88C329mCDxHubOV9R36BBeDKIMbgktzSvVFgn12Lqlnp8ZG/Fu/hrltdQ/oQKlhwH6UoXt04/UqwjJml5npzIYmZIMC/OWW+uzuenohZ/ME0=,iv:vDo49Y+uRZmYYVdIWEw159C57/7ijN4reACy4T78JWI=,tag:7GcppQaGgUs2tXdvATCbcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
