apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PufvS0wbeQA91EIKkqP+PpM4lV6acD29tzoEEHja0ybv69wNv81Pyg==,iv:wtfDMW34I7r6If7aKjYvL+oeNvLWd/gf1qantQLEgBE=,tag:AZppjGBeSLba3Px5TRagxg==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST1FhWE9iaWlHajhuTGEx
        eFdjcGtZVm93aFE3cS83OVZISWFoZ3NrRFU0ClNNRmxYcGdvb1lGUW9zSkRIYStQ
        YjVSNnUxc2c1MzhvS2w1SW5zbUVUdmsKLS0tIHRwKzdkT3NiZkd3Y3FxaDRhNjZF
        U0pQRjlpZnljZFRiMis0MHdtYk8zTVkKq6xQFJGRUUPZTi7fWjX4WrzxyFLCUXzt
        QB3ushs83geLZ84slh11q8pNw6d6chUmb1JvVS4r28gyKNOpHwg5lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T04:15:30Z"
  mac: ENC[AES256_GCM,data:AwvU9mghixH+nQWMc808FoP1P9N7rlK2MxBzla72yT2PJUyFHnhaqEU+6HvBxrvneZKeBD6JVA91r2YmVIXAtO1jKdk3mO6/Hq598mEhXm0XUB5+AIXTBlbs23ArgwTbHp00MxtPh6J2z7BkdZqDVTWbf/tupPM2LP3z775Jc8E=,iv:8GFplOKsth192DzFQk4ow7KnGud4PgWDatcKMpjoJr0=,tag:ChoqwzBuBtcCF794W6q+QA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
