apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:EMPlVpA6ShUekp0LqBj9MtiXgDheHtvkpr5Ix++Bo93RDvrBOtQO0Q==,iv:34tWuFmV6Q4gFNRQNOvXnlVnlur8MOhOek7r8f62Nz0=,tag:V8B1DGvviDiEJTcaP24jMA==,type:str]
sops:
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQnlSYU80V1NZQUJkMWt6
        WDVXWm1KVlI1aXl5cE90S3VLV3FJdkdueEhzCjEvUXJGSWg5aHIva3kwWG9Md3V3
        eWZVMmJsNklHS2hjSlF6UXNNc0xFcmcKLS0tIC9VdHZENmZMQUdudFM5eDZRelEx
        bTJsTzRTN2ZBVjVlMmM3SnlQRVJvZncKlulf5D6G1u43Tg6c5p2wajGKkUjmNNZT
        Qr73FK2UyFjfkkM5pZYoxt4IHVgbPbbMf4wwl4rDB785MYfDHa821A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T05:31:52Z"
  mac: ENC[AES256_GCM,data:+1FO9xJR2sKwixl8Gc3tX3a7V+Hzm611zKeHtW7H/87eedRCfyS2xSZcIliEhTRQms9A7pmgm6Yq8oMKtBIZM4c+PpRDjSh35Q9XtuP8ALbI2yltMnu5O6tSxr1EuBKYlW9pEq6wZPyOPI/pz/KfhiFXD53eDJbGyRD+VaChXNM=,iv:VSanjzBmneD+7AbSBrbXqa+MiCw7z9s+Gi0bYmOkJuI=,tag:p8zC492q9oipqSMLC8XhnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
