---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubero-ui
spec:
  hostnames: ["kubero.parke.dev"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: kubero
          port: 2000
      matches:
        - path:
            type: PathPrefix
            value: /
