apiVersion: v1
kind: Secret
metadata:
    name: kubero-secrets
stringData:
    KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:EM98YLluJdJlT77y/+KT+bntmaOSAWtOOmUKDFfTB2TNPIoZvUWs7w==,iv:kpnBsqro6jnRI2o6/tSMQHEcLELkJKRCtsOSzKzDCbI=,tag:8zPrDipmkx+CEtLbkBe3dQ==,type:str]
    KUBERO_SESSION_KEY: ENC[AES256_GCM,data:7M12BsmdYgzejg6ViAleQ2PIg1NIJCOSOPX81jIRJlS5DPn37Wm8tQ==,iv:CmIvtzwPfdI5e/LjyKi4I7YcosoCWZuIpdPHlLbU2Gk=,tag:s3TCvkrriopFcQ1yIqoQEg==,type:str]
    KUBERO_ADMIN_USERNAME: ENC[AES256_GCM,data:NRISSrs=,iv:mmEvCUyNQ4748eOhsTSrabDgkl2W1eCJRHdFbezz5NQ=,tag:R1gZz+lGU3rnpWGUasc7vg==,type:str]
    KUBERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:fvwIakKI58hfnBhJ,iv:7HlvMusC5LyF0KDkb6HZJDSXKvgzoXO5YDo81wlNqnQ=,tag:BSRWSNRGr7N4kKGvVoZGBA==,type:str]
sops:
    age:
        - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcjJCOXNpZDlkTitDdHdQ
            S09MRVdlaGJXbFdVYTlyUkNhRnc1NU9vQ1JvCmVuYXRuTng4UEtzZGVLZjF2c3Rp
            QU9DckV6eXBxVHkybS9mdkdRdlFPdTQKLS0tIHBUSHByeThmUzY4YTdYUXZKQ2N6
            ZW1IUGlWMVgyTWwxL3lUMmNpWWx6MTgKDP5s92jIATj6QP43UB0n72qzYZ2DRAfi
            kaUZBB9xzEKbeqI7R3WUQBy8UXJR6ghEify/PTBG6DiOCp5KYmiutg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T05:05:52Z"
    mac: ENC[AES256_GCM,data:EyQQg3ioKPXZDDcEocA8haCBeX1DxTOZJUKJwLPYfRGxebf1QLcX3tt1oTvQT6Ss6OjgwOnZfp1i00SKaaOFO7OVKf4FZZNLM5K6bEmBvH7Q1LAH4mYPan5AOJBQ8jWyyLyOeEbDyOn0znDnCQc7eu2AsOHnZGvRu12wRtnwrE8=,iv:1/ycxYF/Oc/mKqSuHb+wI0oxd0VG+KyaHtR8694HgZM=,tag:EaZTC1hUk3xdncwmkpF7hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
