apiVersion: v1
kind: Secret
metadata:
  name: kubero-secrets
stringData:
  KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:ke+qyycM+c3oew0HO57h21xP0M+j55ir1+hGo2qZGHRDOGfCpagwNA==,iv:1iKdApQJyWRd5VXp8NJqeXSsjS9FQgFbnfPUKWVsbVI=,tag:qgYA49Ji/793vZGEdWvXgQ==,type:str]
  KUBERO_SESSION_KEY: ENC[AES256_GCM,data:f46EtUrE8u9cM47w24/ezbCW9sIP8NomsQ7sP7YY2OZIqcVVPSXcIw==,iv:N+amJypf034+Q9mKDA957szzFbXd3BMFNhn6bGryREU=,tag:y5i6+EbU4LDtR5Uzdn4WOg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcUJza3ZENEVXM1o1Vmly
        NmZnM0RVcGdiMHRlNzROVlhuUzF0aVVnK21BCnJYSEx4aHVMaG1jRGJFdWtlMmNj
        Yy9GbWg5OG1LRlBKQzBPQkowZEZSZEUKLS0tIFNaRXRlQUV5Nml2NFdlQ1c4RG1T
        b0tkdGxvUGxld1JVUXpYM0tLb2xReEkKy3GKjN56zHmbjYtXIJyfpQDVL0jLwZIA
        LZj6ZDmxh26PRV/etCZ7pmwoUB8z4rneL710dPYHDzEx0AUZuo76Sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T04:17:20Z"
  mac: ENC[AES256_GCM,data:kpZIXlxOu5aVQ9JAZO415gfmQ1v+RXbikNHKKkdHFJoNu8sN0TfNGqJQqDbQQ6Y7h8OunAsKTj1WG2YyTEo9RrT/7HoeRugaLT1C/FShz2fG1+sqInbHyKkufe98Pd26MtlGn2/qo3LzDHXXPnBML0vd++VKJ8424sxe1TczW1Y=,iv:Mw8Ia1UZ9UlYSnEubqM8CFCCAwQB7v1Ot0ZNnKkWpRk=,tag:rArwjxhVgSNKKZ2zc1VNjw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
