apiVersion: v1
kind: Secret
metadata:
  name: kubero-secrets
stringData:
  KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:EM98YLluJdJlT77y/+KT+bntmaOSAWtOOmUKDFfTB2TNPIoZvUWs7w==,iv:kpnBsqro6jnRI2o6/tSMQHEcLELkJKRCtsOSzKzDCbI=,tag:8zPrDipmkx+CEtLbkBe3dQ==,type:str]
  KUBERO_SESSION_KEY: ENC[AES256_GCM,data:7M12BsmdYgzejg6ViAleQ2PIg1NIJCOSOPX81jIRJlS5DPn37Wm8tQ==,iv:CmIvtzwPfdI5e/LjyKi4I7YcosoCWZuIpdPHlLbU2Gk=,tag:s3TCvkrriopFcQ1yIqoQEg==,type:str]
  KUBERO_ADMIN_USERNAME: ENC[AES256_GCM,data:NRISSrs=,iv:mmEvCUyNQ4748eOhsTSrabDgkl2W1eCJRHdFbezz5NQ=,tag:R1gZz+lGU3rnpWGUasc7vg==,type:str]
  KUBERO_ADMIN_PASSWORD: ENC[AES256_GCM,data:ah/8dwo5glnPjO5aW+2rSLokrE9XSgoW7cV+5wfWtgE=,iv:7bsafpFzxL/Da+LHLxPhN9qtAAzVl15i2XDKJyKFlQQ=,tag:lab7UL8pHsIc0rwvQ5DfYw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1tahav4nn24m4g0vvvxntrumepgpuxga6keyh90lv3lr935j0w3gq4pegcg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcjJCOXNpZDlkTitDdHdQ
        S09MRVdlaGJXbFdVYTlyUkNhRnc1NU9vQ1JvCmVuYXRuTng4UEtzZGVLZjF2c3Rp
        QU9DckV6eXBxVHkybS9mdkdRdlFPdTQKLS0tIHBUSHByeThmUzY4YTdYUXZKQ2N6
        ZW1IUGlWMVgyTWwxL3lUMmNpWWx6MTgKDP5s92jIATj6QP43UB0n72qzYZ2DRAfi
        kaUZBB9xzEKbeqI7R3WUQBy8UXJR6ghEify/PTBG6DiOCp5KYmiutg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T05:04:54Z"
  mac: ENC[AES256_GCM,data:usSNNQZIxJdXr2b0Pl/0XtWXsIIgGGKezncHsHD8P2wm/AKULi2i3itx9FPaZrWNXrQX12LY+3nwvI6vFc1n5giAioWWbd8+YEGEc/xVCVS+5neC9djD92YafFPPtJt234gkd1LUJKbWZevLN8C6mIVOTvxh+V2lNNgiMvziL6k=,iv:Mcl2d/EAGlXW8MYQEk/eYxnH8wPE05aPlfsvYHybhnQ=,tag:SYotqIgJ1zEX+yrJXtwxaw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
