---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled